zh_tw localiztion 1.18.2
SlimeKnights/TinkersConstruct pull request #5192
Opened 2024-03-06 09:13 UTC by StarlightCraft

some localization for Taiwanese, 
book and others

2024-03-06 12:36 UTC, Cactusstudent commented
看起來你們的翻譯文件名稱有些過時，Knightminer在 a994baf這個 commit裡面更改了匠魂手冊的文件結構，我覺得還是修改下比較保險。因為作者未必有時間來著。

2024-03-06 12:57 UTC, Cactusstudent reviewed
大致對 zh_tw.json 看了一遍，由於對台繁原版譯名知之甚少，許多建議還請斟酌後進行改動。

2024-03-06 12:57 UTC, Cactusstudent commented on src/main/resources/assets/tconstruct/lang/zh_tw.json
> +     "tool_stat.tconstruct.projectile_damage": "彈射物傷害：",
這條翻譯原文已從 Projectile Damage -> Projectile Power，簡中改成了“弹射物力量”，不知道繁體這邊怎麼處理。

2024-03-06 12:57 UTC, Cactusstudent commented on src/main/resources/assets/tconstruct/lang/zh_tw.json
> +    "tool_stat.tconstruct.mining_speed": "採掘速度：",
這裡原文經過更改，最好還是考證一下台繁側的譯名，簡中已經從“采掘速度”改成“挖掘速度”以匹配原版了

2024-03-06 12:57 UTC, Cactusstudent commented on src/main/resources/assets/tconstruct/lang/zh_tw.json
> +    "tool_stat.tconstruct.attack_damage": "攻擊傷害：",
這裡的英文原文由Attack換成了Melee，我認為近戰之類的翻譯可能更貼切些，簡中目前使用的是“近戰傷害”

2024-03-06 12:57 UTC, Cactusstudent commented on src/main/resources/assets/tconstruct/lang/zh_tw.json
> +    "tooltip.tconstruct.part.missing_stats": "Material does not support %s",
```suggestion
    "tooltip.tconstruct.part.missing_stats": "材料不支持%s",
```

2024-03-06 12:57 UTC, Cactusstudent commented on src/main/resources/assets/tconstruct/lang/zh_tw.json
> +    "jei.tconstruct.temperature": "%s ℃",
此處留個疑問，並不確定在台繁狀態下顯示該字符大小是否合適，簡中是出現了℃字符顯示過小而選擇使用英文原文中攝氏溫標的表示手段。

2024-03-06 12:57 UTC, Cactusstudent commented on src/main/resources/assets/tconstruct/lang/zh_tw.json
> +    "command.tconstruct.generate_part_textures.finish": "Successfully generated %s part textures in %s s at %s",
```suggestion
    "command.tconstruct.generate_part_textures.finish": "成功生成%s個部件紋理，耗時%s秒，生成位置：%s",```

2024-03-06 12:57 UTC, Cactusstudent commented on src/main/resources/assets/tconstruct/lang/zh_tw.json
> +    "command.tconstruct.generate_part_textures.no_parts": "No part sprites present in resource packs",
```suggestion
    "command.tconstruct.generate_part_textures.no_parts": "資源包中沒有部件信息",
```

2024-03-06 21:24 UTC, KnightMiner commented
As Cactusstudent pointed out, there were some renaming of book pages related to tools and modifiers, make sure you rename the pages you translated accordingly or they will not load on the latest build of the mod (the change was made to help out addons to Tinkers' Construct).

Most of the renames are just prefxing the page name with `tconstruct`, but a couple had page names that did not match the modifier ID, so just reference english if in doubt.

2024-03-10 07:49 UTC, StarskyXIII requested changes
大致看了一下，大量用詞未做在地化轉換。
建議先將 PR 標記為草稿。

2024-03-10 07:49 UTC, StarskyXIII commented on src/main/resources/assets/tconstruct/book/encyclopedia/zh_tw/abilities/armor/boots/tconstruct_path_maker.json
> +      "text": "踩平你走過的草方塊，並留下一條土徑。「延展」強化可以擴大其作用範圍。"
```suggestion
      "text": "踩平你走過的草地，並留下一條土徑。「延展」強化可以擴大其作用範圍。"
```

2024-03-10 07:49 UTC, StarskyXIII commented on src/main/resources/assets/tconstruct/book/encyclopedia/zh_tw/abilities/armor/boots/tconstruct_snowdrift.json
> +      "text": "在寒冷羣系中，可以像雪人一樣在走過的地方留下一層雪。「延展」強化可以擴大其作用範圍。"
```suggestion
      "text": "在寒冷生態域中，可以像雪人一樣在走過的地方留下一層雪。「延展」強化可以擴大其作用範圍。"
```

2024-03-10 07:49 UTC, StarskyXIII commented on src/main/resources/assets/tconstruct/book/encyclopedia/zh_tw/abilities/armor/chestplate/tconstruct_ambidextrous.json
> +      "text": "允許你使用副手攻擊。副手將會受到所有對主手的空手強化的加成。"
```suggestion
      "text": "允許你使用非慣用手攻擊。並且獲得所有對慣用手空手強化的加成。"
```

2024-03-10 07:49 UTC, StarskyXIII commented on src/main/resources/assets/tconstruct/book/encyclopedia/zh_tw/abilities/armor/shield/tconstruct_boundless.json
> +      "text": "將部分強化（如「保護」「龍裔」「潛影殼」等）的加成上限從80%提升至90%。如果加持于兩件裝備，則進一步從90%提升至95%。"
```suggestion
      "text": "將部分強化（如「保護」「龍裔」「界伏殼」等）的加成上限從80%提升至90%。如果加持於兩件裝備，則進一步從90%提升至95%。"
```

2024-03-10 07:54 UTC, Cactusstudent commented
順帶一提，你的大多數譯名和翻譯都是由簡體中文轉換來的，使用的版本也有些陳舊，可以以目前庫中和 #5191 的簡體中文作為參考，由於簡體中文和台繁的術語與語言環境不盡相同，還請在進行在地化工作時謹慎行事。

2024-03-10 08:00 UTC, StarskyXIII commented
還有若使用簡體翻譯，希望你能在文中敘述給予適當地提及與表彰，
簡體翻譯也是由大多數玩家耗費大量時間與心血製作而成，這是對這些譯者們的基本尊重。

2024-03-14 10:12 UTC, StarlightCraft commented
我也有此打算，你建議該在哪處提及呢？

2024-03-14 12:03 UTC, Cactusstudent commented
我認為寫在zh_tw.json的最後，通過新增一個用於注釋的鍵來寫比較好。另外，簡中譯名在本庫遵循MIT協議，請註明

2024-03-15 08:38 UTC, StarlightCraft commented
你的意思是註明甚麼？

2024-03-19 11:13 UTC, StarskyXIII requested changes
辛苦了，花費那麼多時間進行在地化工作。
目前只檢查了一半，有空再把剩下的檢查完。

2024-03-19 11:13 UTC, StarskyXIII commented on src/main/resources/assets/tconstruct/book/encyclopedia/zh_tw/abilities/armor.json
> +    { "text": "\n• 頭盔可以通過綁定按鍵觸發特殊效果。", "paragraph": true },
繁中這邊的 `通過`，意思是穿越某個地方，也就是 `Pass through`
其他地方的 `通過` 也需要替換
```suggestion
    { "text": "\n• 頭盔可以透過綁定按鍵觸發特殊效果。", "paragraph": true },
```

2024-03-19 11:13 UTC, StarskyXIII commented on src/main/resources/assets/tconstruct/book/encyclopedia/zh_tw/abilities/armor.json
> +    { "text": "\n• 盾牌的反擊會更為強力，但部分強化只會在 格擋時起效。" }
其他地方的 `起效` 也需要替換
```suggestion
    { "text": "\n• 盾牌的反擊會更為強力，但部分強化只會在格擋時生效。" }
```

2024-03-19 11:13 UTC, StarskyXIII commented on src/main/resources/assets/tconstruct/book/encyclopedia/zh_tw/upgrades/armor/boots/tconstruct_soulspeed.json
> +      "text": "在靈魂沙上的移動速度+40.5%，後續每級移動速度+10.5%，能夠減少靈魂沙帶來的減速效果。"
原版 `Soul Sand` 翻譯為 `靈魂砂`，需統一用字。
```suggestion
      "text": "在靈魂砂上的移動速度+40.5%，後續每級移動速度+10.5%，能夠減少靈魂砂帶來的減速效果。"
```

2024-03-19 11:13 UTC, StarskyXIII commented on src/main/resources/assets/tconstruct/book/encyclopedia/zh_tw/upgrades/armor/general/tconstruct_freezing.json
> +        "text": "每級有15%的概率冰凍攻擊者4秒（每級+4秒），施加緩速效果並且造成傷害。多件盔甲的效果將會堆疊。"
繁中這邊為 `機率`，其餘地方也需要替換
```suggestion
        "text": "每級有15%的機率冰凍攻擊者4秒（每級+4秒），施加緩速效果並且造成傷害。多件盔甲的效果將會堆疊。"
```

2024-03-19 11:13 UTC, StarskyXIII commented on src/main/resources/assets/tconstruct/book/fantastic_foundry/zh_tw/blazing_blood/piglin_bartering.json
> +  "title": "豬靈以物易物",
```suggestion
  "title": "豬布林以物易物",
```

2024-03-19 11:13 UTC, StarskyXIII commented on src/main/resources/assets/tconstruct/book/materials_and_you/zh_tw/intro/welcome.json
> +      "text": "如果你想知道最新版本有什麼變化，請前往 「What's New」頁面，可以在GitHub頁面或是 SlimeKnights的Discord伺服器找到跳轉鏈接。 但遺憾的是，我沒搞清楚怎麼在書中新增連結， 所以我沒辦法直接讓你跳轉。",
```suggestion
      "text": "如果你想知道最新版本有什麼變化，請前往 「What's New」頁面，可以在GitHub頁面或是 SlimeKnights的Discord伺服器找到跳轉連結。 但遺憾的是，我沒搞清楚怎麼在書中新增連結， 所以我沒辦法直接讓你跳轉。",
```

2024-03-19 11:18 UTC, StarskyXIII commented
@Cactusstudent 請教一下，近程跟近戰的意思有差別嗎？
我自己覺得 `近程` 唸起來怪怪的，想統一成 `近戰`。

還有空格會造成手冊換行問題嗎？
不然有不少地方想要求中英文字之間要留空（
不過這部分算吹毛求疵，作業量太大不必採納意見就是了。

2024-03-19 11:48 UTC, Cactusstudent commented
1. 近程在簡中里並無什麼特殊含義，主要想求一個與“遠程”對賬，如果更改我認為沒有問題，因為Melee正是近戰的意思。
2. 簡中會導致空格換行問題，目前採取的措施是每20個漢字之間添加一個空格避免這種情況，但是處理起來效果只能說是差強人意。
3. 中英文字符之間留空我覺得是非必要的，不過留下就可能會導致2的問題。還請考慮。

2024-03-20 09:16 UTC, StarlightCraft commented
另外，翻譯時該採取常用稱戶或是官方譯名？
``潛行`在繁中側通常稱為`蹲下`，但官方譯名為`潛行`
`副手`和`非慣用手`也是一樣情形

2024-03-20 09:20 UTC, StarskyXIII commented
為了翻譯一致性，我個人會建議使用官方譯名
以下是官方中英名詞翻譯對照表，提供參考使用：
https://github.com/TeamKugimiya/Language-Comparison-List/blob/main/1.19.4/list.txt

2024-06-01 22:08 UTC, merged